# -*- coding: utf-8 -*-
"""Corral_G_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-6Ort0-340IjihinPPGKF9tEv-sJv5xk
"""

# ==========================================================================
# 1. PREPARAR EL ENTORNO
# ==========================================================================
# Rúbrica: Ejecutar el programa para asegurarse de que funcione correctamente.
!pip install -q streamlit wordcloud plotly nltk

# ==========================================================================
# 2. IMPORTACIONES Y CONFIGURACIÓN
# ==========================================================================
# Rúbrica: Cada sección tiene un comentario que explica qué hace.
import matplotlib.pyplot as plt
import nltk
import numpy as np
import pandas as pd
import plotly.express as px
import streamlit as st   # <-- Fundamental para crear el panel web interactivo
from wordcloud import WordCloud, STOPWORDS

# VADER necesita descargar su diccionario la primera vez.
nltk.download("vader_lexicon", quiet=True)
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Un color por categoría, usado en todo el cuaderno.
COLORES = {"Positivo": "#17A2A2", "Neutral": "#E8A33D", "Negativo": "#C0392B"}
MAPAS = {"Positivo": "Greens", "Neutral": "Oranges", "Negativo": "Reds"}
ORDEN = ["Positivo", "Neutral", "Negativo"]

print("Entorno listo.")

# ==========================================================================
# 3. INTERFAZ WEB Y CARGA DE DATOS
# ==========================================================================
# Rúbrica: Tiene título (st.title) y descripción (st.write).
# Rúbrica: Carga tu CSV y míralo.

st.title("Panel de Análisis: EcoSmart Backpack")
st.write("Este panel web interactivo visualiza los datos de reseñas de clientes sobre la mochila EcoSmart Backpack, clasificando los sentimientos y mostrando los términos más frecuentes.")

# Carga de datos desde el CSV
df = pd.read_csv("Backpack_Reviews_with_Ratings (5).csv")

print("Archivo cargado con éxito.")

# ==========================================================================
# 4. EXPLORACIÓN INICIAL
# ==========================================================================
# Rúbrica: Agregar comentarios en su código para explicar qué hace cada sección.
print("Filas y columnas:", df.shape)
print("\nCalificaciones:")
print(df["Rating"].value_counts().sort_index().to_string())
print("\nTextos distintos:", df["Review"].nunique(), "de", len(df))
print("Valores faltantes:", df.isna().sum().sum())

df.head()

# ==========================================================================
# 5. CLASIFICAR EL SENTIMIENTO CON VADER
# ==========================================================================
# Rúbrica: Clasifica con VADER y cruza contra el Rating.
sia = SentimentIntensityAnalyzer()

# Prueba rápida para verificar la herramienta
for texto in [
    "The shoulder straps are very comfortable and padded.",
    "The zipper broke on the second day of use.",
]:
  print(texto)
  print(sia.polarity_scores(texto), "\n")

# ==========================================================================
# 6. APLICAR SENTIMIENTO AL DATAFRAME
# ==========================================================================
# Rúbrica: Agregar comentarios en su código para explicar qué hace cada sección.
df["Compound"] = df["Review"].apply(
    lambda texto: sia.polarity_scores(texto)["compound"]
)

def clasificar(compound):
  """Traduce el puntaje de VADER a una categoría."""
  if compound >= 0.05:
    return "Positivo"
  if compound <= -0.05:
    return "Negativo"
  return "Neutral"

df["Sentimiento"] = df["Compound"].apply(clasificar)
print(df["Sentimiento"].value_counts().to_string())

# ==========================================================================
# 7. VERIFICAR LA CLASIFICACIÓN CONTRA EL RATING
# ==========================================================================
# Rúbrica: Cruza contra el Rating (pd.crosstab).
# Genera una tabla cruzada para comprobar que el sentimiento coincide con las estrellas.
print(pd.crosstab(df["Rating"], df["Sentimiento"]).to_string())

# ==========================================================================
# 8. ANÁLISIS DE DISCREPANCIAS
# ==========================================================================
# Rúbrica: Agregar comentarios en su código para explicar qué hace cada sección.
discrepancias = df[(df["Rating"] <= 2) & (df["Sentimiento"] != "Negativo")]
bajas = (df["Rating"] <= 2).sum()

print(f"Reseñas de 1-2 estrellas: {bajas}")
print(
    f"No clasificadas como negativas: {len(discrepancias)}"
    f" ({100 * len(discrepancias) / bajas:.0f}%)\n"
)

for texto in discrepancias["Review"].unique()[:6]:
  print("-", texto)

# ==========================================================================
# 9. VISUALIZACIÓN — RESEÑAS POR CATEGORÍA
# ==========================================================================
# Rúbrica: Muestra el conteo de las tres categorías (positivo, neutral y negativo).
conteo = df["Sentimiento"].value_counts().reset_index()
conteo.columns = ["Sentimiento", "Cantidad"]

st.subheader("Número de opiniones por categoría")

fig = px.bar(
    conteo,
    x="Sentimiento",
    y="Cantidad",
    color="Sentimiento",
    color_discrete_map=COLORES,
    category_orders={"Sentimiento": ORDEN},
    text="Cantidad",
    title="Número de reseñas por categoría de sentimiento",
)
fig.update_layout(height=420, template="plotly_white", showlegend=False)

# Visualización para Streamlit
st.plotly_chart(fig)

# Visualización para ver el resultado inmediatamente en Google Colab
fig.show()

# ==========================================================================
# 10. VISUALIZACIÓN — NUBES DE PALABRAS
# ==========================================================================
# Rúbrica: Muestra TRES nubes de palabras – uno para cada categoría de revisión.
# Rúbrica: Ajusta las palabras a ignorar con los términos de tu producto.

st.subheader("Nubes de palabras por categoría de sentimiento")

IGNORAR = set(STOPWORDS) | {"backpack", "bag", "product", "one", "will", "now", "ecosmart"}

fig, ejes = plt.subplots(1, 3, figsize=(16, 4.5))

for eje, categoria in zip(ejes, ORDEN):
  textos = df[df["Sentimiento"] == categoria]["Review"]
  texto_unido = " ".join(textos)

  if texto_unido.strip():
    nube = WordCloud(
        width=800,
        height=500,
        background_color="white",
        colormap=MAPAS[categoria],
        stopwords=IGNORAR,
        max_words=60,
        collocations=False,
    ).generate(texto_unido)
    eje.imshow(nube)
    eje.set_title(f"{categoria} ({len(textos)} reseñas)", fontweight="bold")
  else:
    eje.set_title(f"{categoria} (sin reseñas)")

  eje.axis("off")

plt.tight_layout()

# Visualización para Streamlit
st.pyplot(fig)

# Visualización para ver el resultado inmediatamente en Google Colab
plt.show()

print("Fin del cuaderno.")

# 11. CONSULTAR UNA API (Open-Meteo, sin clave)
import requests

respuesta = requests.get(
    "https://api.open-meteo.com/v1/forecast",
    params={
        "latitude": -33.45,       # Santiago de Chile
        "longitude": -70.66,
        "daily": "temperature_2m_max,temperature_2m_min",
        "timezone": "auto",
        "past_days": 7,
        "forecast_days": 7,
    },
    timeout=10,                    # no esperar para siempre
)

print("Código de estado:", respuesta.status_code)
print("URL construida:", respuesta.url[:100], "...")

# Procesar los datos
datos = respuesta.json()["daily"]

# Opcional: Convertirlo a DataFrame para manipularlo mejor
import pandas as pd
df_clima = pd.DataFrame(datos)
print("\nPrimeros días de datos meteorológicos:")
print(df_clima.head())
print("\nClaves recibidas:", list(datos.keys()))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app_v1.py
# import streamlit as st
# 
# st.title("¡Hola! Mi primera aplicación en Streamlit")
# st.write("Si estás viendo esto, el servidor y el túnel están funcionando correctamente.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app_v1.py
# import streamlit as st
# 
# # Título de la página
# st.title("EcoHydro Bottle - Panel de Reseñas de Clientes")
# 
# # Descripción de la página
# st.write("Análisis de sentimiento de las reseñas de clientes de la botella EcoHydro.")

# ==========================================================================
# 10. EJECUTAR LA APLICACIÓN DESDE COLAB
# ==========================================================================
# QUITA LOS # PARA LANZAR LA APLICACIÓN
# ---------------------------------------------------------------
# Paso 1: Streamlit en segundo plano. El & final libera la celda.
!streamlit run app_v1.py --server.port 8501 &> logs.txt &

# Paso 2: la contraseña del túnel es la IP pública de esta sesión.
!curl -s https://loca.lt/mytunnelpassword

print("Quita los # de las dos líneas para ejecutar.")

# QUITA EL # PARA ABRIR EL TÚNEL
# ---------------------------------------------------------------
# Esta celda se queda ejecutando mientras el túnel esté activo.
!npx --yes localtunnel --port 8501

# Si localtunnel falla, alternativa con cloudflared:
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared && ./cloudflared tunnel --url http://localhost:8501

print("Quita el # para abrir el túnel.")

# Para detener el servidor antes de relanzar:
# !pkill -f streamlit

print("Celda de apagado.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# # ==========================================================================
# # PANEL DE RESEÑAS - aplicación completa
# # ==========================================================================
# import matplotlib.pyplot as plt
# import nltk
# import pandas as pd
# import plotly.express as px
# import requests
# import streamlit as st
# from wordcloud import WordCloud, STOPWORDS
# 
# nltk.download("vader_lexicon", quiet=True)
# from nltk.sentiment.vader import SentimentIntensityAnalyzer
# 
# COLORES = {"Positivo": "#17A2A2", "Neutral": "#E8A33D", "Negativo": "#C0392B"}
# MAPAS = {"Positivo": "Greens", "Neutral": "Oranges", "Negativo": "Reds"}
# ORDEN = ["Positivo", "Neutral", "Negativo"]
# IGNORAR = set(STOPWORDS) | {"backpack", "bag", "product", "one", "will", "now"}
# 
# 
# @st.cache_data
# def cargar_datos():
#     sia = SentimentIntensityAnalyzer()
#     # Archivo de mochilas configurado correctamente
#     datos = pd.read_csv("Backpack_Reviews_with_Ratings (5).csv")
# 
#     datos["Compound"] = datos["Review"].apply(
#         lambda texto: sia.polarity_scores(str(texto))["compound"])
#     datos["Sentimiento"] = datos["Compound"].apply(
#         lambda c: "Positivo" if c >= 0.05 else ("Negativo" if c <= -0.05 else "Neutral"))
#     return datos
# 
# 
# @st.cache_data(ttl=1800)
# def obtener_clima():
#     respuesta = requests.get(
#         "https://api.open-meteo.com/v1/forecast",
#         params={"latitude": -32.93, "longitude": -71.13,
#                 "daily": "temperature_2m_max,temperature_2m_min",
#                 "timezone": "auto", "past_days": 7, "forecast_days": 7},
#         timeout=10)
#     respuesta.raise_for_status()
#     datos = respuesta.json()["daily"]
#     return pd.DataFrame({"Fecha": pd.to_datetime(datos["time"]),
#                          "T_Max": datos["temperature_2m_max"],
#                          "T_Min": datos["temperature_2m_min"]})
# 
# 
# st.set_page_config(page_title="Mochilas - Reseñas", layout="wide")
# 
# # --- Título de la página ---------------------------------------------------
# st.title("Mochilas - Panel de Reseñas de Clientes")
# 
# # --- Descripción de la página ----------------------------------------------
# st.write("Este panel muestra el análisis de sentimiento de las reseñas de clientes sobre las "
#          "mochilas, clasificadas con VADER en tres categorías.")
# 
# df = cargar_datos()
# 
# # --- Visualización 1: reseñas por categoría --------------------------------
# st.subheader("Reseñas por categoría de sentimiento")
# 
# conteo = df["Sentimiento"].value_counts().reset_index()
# conteo.columns = ["Sentimiento", "Cantidad"]
# 
# fig = px.bar(conteo, x="Sentimiento", y="Cantidad", color="Sentimiento",
#              color_discrete_map=COLORES,
#              category_orders={"Sentimiento": ORDEN},
#              text="Cantidad")
# fig.update_layout(height=420, template="plotly_white", showlegend=False)
# st.plotly_chart(fig, use_container_width=True)
# 
# # --- Visualización 2: una nube de palabras por categoría -------------------
# st.subheader("Nubes de palabras por categoría")
# 
# columnas = st.columns(3)
# for columna, categoria in zip(columnas, ORDEN):
#     textos = df[df["Sentimiento"] == categoria]["Review"].dropna()
#     texto_unido = " ".join(textos.astype(str))
# 
#     columna.markdown(f"**{categoria}** ({len(textos)} reseñas)")
# 
#     if texto_unido.strip():
#         nube = WordCloud(width=700, height=450, background_color="white",
#                          colormap=MAPAS[categoria], stopwords=IGNORAR,
#                          max_words=60, collocations=False).generate(texto_unido)
#         figura, eje = plt.subplots(figsize=(7, 4.5))
#         eje.imshow(nube)
#         eje.axis("off")
#         columna.pyplot(figura)
#     else:
#         columna.info(f"Sin reseñas en la categoría {categoria}.")
# 
# # --- Datos externos desde una API ------------------------------------------
# st.subheader("Temperatura diaria en Villa Alemana (API Open-Meteo)")
# 
# try:
#     clima = obtener_clima()
#     fig_clima = px.line(clima, x="Fecha", y=["T_Max", "T_Min"], markers=True,
#                         labels={"value": "°C", "variable": "Serie"})
#     fig_clima.update_layout(height=380, template="plotly_white")
#     st.plotly_chart(fig_clima, use_container_width=True)
# except requests.exceptions.RequestException:
#     st.warning("No se pudo consultar la API en este momento.")

import os
print("Archivos creados:", [f for f in os.listdir() if f.endswith(".py")])

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dash_app.py
# # ==========================================================================
# # PANEL DE RESEÑAS - la misma aplicación, escrita en Dash
# # ==========================================================================
# import base64
# import io
# 
# import matplotlib
# matplotlib.use("Agg")        # backend sin ventana, necesario en un servidor
# import nltk
# import pandas as pd
# import plotly.express as px
# from dash import Dash, dcc, html
# from wordcloud import WordCloud, STOPWORDS
# 
# nltk.download("vader_lexicon", quiet=True)
# from nltk.sentiment.vader import SentimentIntensityAnalyzer
# 
# COLORES = {"Positivo": "#17A2A2", "Neutral": "#E8A33D", "Negativo": "#C0392B"}
# MAPAS = {"Positivo": "Greens", "Neutral": "Oranges", "Negativo": "Reds"}
# ORDEN = ["Positivo", "Neutral", "Negativo"]
# IGNORAR = set(STOPWORDS) | {"backpack", "bag", "product", "one", "will", "now"}
# 
# # Preparación de datos: igual que en Streamlit.
# sia = SentimentIntensityAnalyzer()
# df = pd.read_csv("Backpack_Reviews_with_Ratings (5).csv")
# df["Compound"] = df["Review"].apply(lambda t: sia.polarity_scores(str(t))["compound"])
# df["Sentimiento"] = df["Compound"].apply(
#     lambda c: "Positivo" if c >= 0.05 else ("Negativo" if c <= -0.05 else "Neutral"))
# 
# conteo = df["Sentimiento"].value_counts().reset_index()
# conteo.columns = ["Sentimiento", "Cantidad"]
# 
# fig = px.bar(conteo, x="Sentimiento", y="Cantidad", color="Sentimiento",
#              color_discrete_map=COLORES, category_orders={"Sentimiento": ORDEN},
#              text="Cantidad")
# fig.update_layout(template="plotly_white", showlegend=False)
# 
# 
# def nube_como_imagen(categoria):
#     """Genera la nube y la devuelve en base64: Dash no acepta figuras de matplotlib."""
#     textos = " ".join(df[df["Sentimiento"] == categoria]["Review"].astype(str))
#     nube = WordCloud(width=700, height=450, background_color="white",
#                      colormap=MAPAS[categoria], stopwords=IGNORAR,
#                      max_words=60, collocations=False).generate(textos)
# 
#     memoria = io.BytesIO()
#     nube.to_image().save(memoria, format="PNG")
#     return "data:image/png;base64," + base64.b64encode(memoria.getvalue()).decode()
# 
# 
# app = Dash(__name__)
# app.title = "Mochilas - Reseñas"
# 
# app.layout = html.Div(style={"maxWidth": "1100px", "margin": "0 auto",
#                              "fontFamily": "sans-serif", "padding": "20px"},
#                       children=[
#     # Título de la página
#     html.H1("Mochilas - Panel de Reseñas de Clientes"),
# 
#     # Descripción de la página
#     html.P("Este panel muestra el análisis de sentimiento de las reseñas de clientes "
#            "sobre las mochilas, clasificadas con VADER."),
# 
#     # Visualización 1
#     html.H3("Reseñas por categoría de sentimiento"),
#     dcc.Graph(figure=fig),
# 
#     # Visualización 2
#     html.H3("Nubes de palabras por categoría"),
#     html.Div(style={"display": "flex", "gap": "10px"}, children=[
#         html.Div(style={"flex": "1"}, children=[
#             html.H4(categoria, style={"color": COLORES[categoria]}),
#             html.Img(src=nube_como_imagen(categoria), style={"width": "100%"}),
#         ]) for categoria in ORDEN
#     ]),
# ])
# 
# if __name__ == "__main__":
#     app.run(debug=False, port=8501)

# ==========================================================================
# 13. TU TURNO
# ==========================================================================
# Este cuaderno resolvió un panel para la BOTELLA.
# Tu tarea pide un panel para OTRO producto: el procedimiento es el mismo,
# los datos y las palabras son distintos.
#
# RUTA DE TRABAJO
#   1. Carga tu CSV y míralo: filas, textos distintos, calificaciones, nulos.
#   2. Clasifica con VADER y cruza contra el Rating (pd.crosstab).
#   3. Construye las dos visualizaciones AQUÍ, en el cuaderno.
#   4. Ajusta las palabras a ignorar con los términos de tu producto.
#   5. Recién entonces escribe el .py y lánzalo.
#
# ANTES DE ENTREGAR
#   [ ] El archivo se llama según el formato del enunciado
#   [ ] Corre completo, desde cero, sin errores
#   [ ] Tiene título (st.title) y descripción (st.write)
#   [ ] Muestra el conteo de las tres categorías
#   [ ] Muestra TRES nubes de palabras, una por categoría
#   [ ] Cada sección tiene un comentario que explica qué hace
#   [ ] Los comentarios indican qué parte responde a cada criterio de la rúbrica
#
# Las palabras de tu producto no son las de una botella: si copias las
# stopwords de este cuaderno, vas a filtrar palabras que no existen en tus
# datos. El paso 1 no es opcional.

print("Fin del cuaderno.")